services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=example123
      - MYSQL_DATABASE=db_jwt
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - jwtnetwork
    dns:
      - 8.8.8.8
      - 8.8.4.4

  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    ports:
      - 3002:3002
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=example123
      - DB_NAME=db_jwt
      - DB_PORT=3306
      - JWT_SECRET=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyNTYzNTE5MSwiaWF0IjoxNzI1NjM1MTkxfQ.tsMdIhEAZ3dBmpAkYtWQosM4RXQ3J8AADH45UheFFtQ
    stdin_open: true
    tty: true
    extra_hosts:
      - "api.jwt.zeonkun.tech:195.35.6.208"
    networks:
      - jwtnetwork
    command: >
      sh -c "while ! nc -z mysqldb 3306; do sleep 1; done;
             npm run db:create && npm run db:migrate && npm start"

volumes: 
  db:

networks:
  jwtnetwork:
